### ISSUE TITLE
Make CSV export cleaner and fully comprehensive

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#100]
### Business Case
Each event has individual communication, judging and other needs. We've aligned as near as possible on all these but there will always be individual needs. Therefore we need clean, manageable and ordered CSV exports where each event can build what they need from the above using MailChimp, Sheets, Data Studios etc.

### Current Behaviour
CSV export _currently_ exports the majority of the project information in one file grouped by project.

### What we need
Need the ability to export 2 files that together contain *all the information* about the projects and participants. One with all the project information with the project ID and one with all the user information organised by project ID and role ID. Note: I do mean all database data. This is essentially a cleaned database dump.

**Comment by Wardormeur** [comment]
As discussed last time, I think that exporting directly to a sheet would be cleaner in some ways
The reason for it is : 
 - only one and one source of truth
 - no CSVs with personal data on laptop
That's slightly more work, of course, but cleaner as well

**Comment by conoramurphy** [comment]
I'd love a direct export, as would the events teams.

 It's essentially a "measure a piece of string for me" type of question as to whether we go that way. Do you want to edit this ticket to be an "investigate" ticket and see what sort of work it would be before we make that call. If we do go that way also Google BigQuery might be a sensible intermediary, a wild guess that it might be easier to manage that data connection.

**Comment by Wardormeur** [comment]
By direct export, you mean CSV or -> to google sheet ?
And big no for BigQuery : it's way too opinionated to be usable for anyone non-tech

**Comment by conoramurphy** [comment]
"direct export" I meant what you said >> "I think that exporting directly to a sheet would be cleaner in some ways". 

Sorry and I meant Big Query as a middle point. And then point that at a Google Sheet. I've no idea how hard/easy a google sheet direct export is. So was probably a pointless suggestion.

**Comment by Wardormeur** [comment]
Can't be done. The spreadsheet API requires OAuth autorisation (because it writes to a >user< account), and there only client-side flow is supported. That means we'd need to expose the bot to everybody using the export.
That's such a regression and a cost at that point that I'm heavily considering a skip

**Comment by Wardormeur** [comment]
PR : https://github.com/CoderDojo/coolest-platform/pull/120
