### ISSUE TITLE
Language standardisation of 2019

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#101]
We're going to go off this sheet and the text should just be in master for all platforms.
https://docs.google.com/spreadsheets/d/1DmXFCIFhDRjRg60ENQo_cSHVjjW7qUzWMVtjOZzkysQ/edit#gid=1527876900

#### On the first page
- [ ] Change 13 to 16
- [ ] Add to the tick box, "Read more about our Privacy Policy here. [https://www.raspberrypi.org/privacy/]"
#### On the second page

- [ ] Change the attend questions and answers

- [ ] Change the 3rd gender option

 - [ ] Make the phone hint `123 456 7890`

#### Confirmation Page

- [ ] Change in to at

### Note
Since there's several changes it's hard to review this stuff without all the different issues merged. So this will need a review once done by Conor to make sure he has not messed up, assuming he can kick it up locally.

**Comment by Wardormeur** [comment]
PR : https://github.com/CoderDojo/coolest-platform/pull/132

**Comment by conoramurphy** [comment]
Phone number hint still needs to be changed doesn't it?
