### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#104]
### Business Case
The platform is a global event, has a new unified brand that overtakes all previous brands. We need to use the latest branding.

### Task
Replace the current 3 logos with only the main Coolest Projects logo on both the platform and in the emails. https://coolestprojects.org/_nuxt/img/33df4a4.svg
Also update the favicon and anywhere else a logo is used.

**Comment by damienh** [comment]
@conoramurphy I am guessing we will be wanting to update favicons and app icons as well to the new logo?

**Comment by conoramurphy** [comment]
Yes. (App icons?) But yes anywhere a logo of any type is mentioned this should replace it. I'll update ticket accordingly.
