### ISSUE TITLE
Set limits on fields to length of 2018 desksheets

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#125]
#### Business case

We had to trim some titles and desciptions last year which made them look quite poor on the desksheets lanyards. Setting more sensible limits should prevent this

#### Task
- [ ] Update validation to stop anyone having a title over 45 characters long
- [ ] Update validation to stop anyone having a Description over 300 characters long

**Comment by conoramurphy** [comment]
`A project description cannot be longer than 1000 characters` is the current one. Switch to.

`This description will be printed on a desksheet where you present your project. Please keep it below 300 characters so it's easily readable.`

**Comment by Wardormeur** [comment]
Current one for title is `A project name cannot be longer than 45 characters`
Keep it or change it ? @conoramurphy

**Comment by conoramurphy** [comment]
that's fine.
