### ISSUE TITLE
Different Categories in all Events

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#130]
### International
- Visual programming
- Web
- Games
- Mobile Apps
- Hardware
- 3D Design & animation
- Advanced programming (Sub Zero)

### USA & UK
- Visual programming
- Web
- Games
- Mobile Apps
- Hardware

## Shortcodes for categories
Visual programming -> `VIS`
Web -> `WEB`
Games -> `GAM`
Mobile Apps -> `MOB`
Hardware -> `HW`
3D Design & animation -> `DES`
Advanced programming (Sub Zero) -> `ADV`

**Comment by Wardormeur** [comment]
Is VISual prog Scratch?
If we're changing the shortcode (continue the split of age), we need to update the generation of seats

**Comment by conoramurphy** [comment]
Yes Visual programming is scratch (just now allows other types of vis programming).

**Comment by Wardormeur** [comment]
Is the split age still a thing ?
Is the short code changing ? from (SC to VIS) ?

**Comment by conoramurphy** [comment]
I've no idea. Anyway we can just wrap the seating questions until January? Any answers we get on them will just be guesses until we're a bit nearer.

**Comment by Wardormeur** [comment]
I'd prefer not to? Categories are being used to save projects

**Comment by conoramurphy** [comment]
I realise that but does seating need to be fully functional this week?

**Comment by Wardormeur** [comment]
It means that we have to migrate over every registered projects if the categories are wrong. Seating is a side-effect of non-well defined categories

**Comment by conoramurphy** [comment]
I feel like we're not talking about the same thing. 

The categories are set I've been told. So no migrations needed there.

But things like Split age and whether the shortcodes will be sued for seating are not. But that's just affecting the script is it not?

**Comment by Wardormeur** [comment]
Categories and shortcode (SC, HW,...) are part of the categories
When we save an event, we save the shortcode.

**Comment by conoramurphy** [comment]
Ah ok. I've put the shortcodes I'd choose below then. Does this help?

I'll sit with Rosa when she's back from lunch and decide the shortcodes then.

**Comment by conoramurphy** [comment]
Shortcodes.

Visual programming -> VIS
Web -> WEB
Games -> GAM
Mobile Apps -> MOB
Hardware -> HW
3D Design & animation -> DES
Advanced programming (Sub Zero) -> ADV

**Comment by Wardormeur** [comment]
Done, manual migration as always as each event is different
