### ISSUE TITLE
Improvements to emails

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#131]
### Business logic

Use cases we're hoping to tweak the email depending on the event.

- Allowing a different image per event in the emails if we have the event code sent to the email
- Allowing much better-tweaked register vs apply language if we send that register true/false to the email
- Allowing us to tweak things easier without code changes as data comes in.

My proposal is that a move to dynamic templates (which is just the standard one now) would allow us to solve these things.

### Task for Devs

Move the SendGrid API to use dynamic content.

This involves changing the JSON I believe.

I also would like whether it's register AND the event code sent over as well. Annoyingly you can't check for equality in handlebars (the template syntax). So I need it in something like the below

```
{
  "verificationSentence": "sure idk",
  "projectName": "myLittle Scratch Project",
  "eventName": "Coolest projects 2019",
  "eventDate": "21st of January",
  "eventLocation": "Blanchardstown Racecourse",
  "eventWebsite": "www.coolexample.com",
  "eventManageLink": "registerInt.coolestprojects.org",
  "usa2019": "true",
  "register": "true"
}
```
The "confirm your project" id is `d-47688ce306734a92bf6211b0e9bfccc9`
The "magic link" id is `d-fdb597373fb14b8fba7f7938a05ca0e3`
The "you've registered a project" ID `d-23da4e90859043bf81d7c3c1d4c14a5c`

I can change this if need be. Just put here as an example of what I currently use.

### Task for Conor

Once the above is set. Do examples that Rosa etc. can use in customising per event.

**Comment by Wardormeur** [comment]
What are you trying to achieve here? What's the functional role of that? off platform is "not" easier to customize as we still have to set the variables that needs changes to Sendgrid.
What changes is that we offer more chances for whoever to break the templates.
Unless there is a clear use-case, I don't see the point

**Comment by Wardormeur** [comment]
Particularly when the templates are not different per instance

**Comment by conoramurphy** [comment]
Uses we already know about.
- Allowing a different image per event in the emails
- Allowing better-tweaked register vs apply language
- Allowing us to tweak things easier without code changes as data comes in.

**Comment by Wardormeur** [comment]
1 - The templates are not different per instance : we share them.
2 - the value needs to be sent by the platform
3 - that's already the case ? Anything else needs changing on the platform

**Comment by Wardormeur** [comment]
Sorry about all that, but instead of defining that we need to move to dynamic templates (which is a technical choice..), maybe a functional description of what you wanted to use it to (making the template varying over the different events) would had been easier to understand.
Moving to dynamic might break our current integration, due to us using a lib for it, so that's something to look at.
As much as possible, I'd prefer to keep all templates on the same version of Sendgrid's API
For recognition of the event, defining the key could be enough, but I'd consider using only "us" "uk" or "int", unless you want to update it every year. This will require a new env_var as they don't "know" which region each pod is running.
For register, we can use a boolean considering it's a 2 state machine.
What I'd like not to see, is to have the variables overwritten by the template and have people complaining it's not working the way they expect it (email, website, etc).

**Comment by conoramurphy** [comment]
I re-edited the description up top to be more functional.

- `all templates on the same version of Sendgrid's API` Yes absolutely. Currently, there are only 2 templates. I'll move the other one over as well as soon as I'm sure we're doing the move. The first one was the test.
- `I'd consider using only "us" "uk" or "int"` We could, but it's very low effort to tweak the event variable once a year in the email.
- `register` : Yep just checked. "register":true|false as a boolean works or something like that.

`What I'd like not to see, is to have the variables overwritten by the template `  I don't think this would be the case. In the end it's the same email. Just now would much more accurately reflect each event. But the actions are basically identical this year.

**Comment by Wardormeur** [comment]
We could reuse the env var for budiling the frontend then (the slug), it'll be "xx-2019" (xx = cp, na, uk currently)

**Comment by conoramurphy** [comment]
Ya whatever makes sense there. (usa now but not much difference either way)

**Comment by Wardormeur** [comment]
updated

**Comment by Wardormeur** [comment]
Do you plan on handling the different confirm email (https://github.com/CoderDojo/coolest-platform/issues/99) with this ? (like, step1, step2, step3)

**Comment by Wardormeur** [comment]
TBD : verify batching works with dynamic template once the template is created

**Comment by Wardormeur** [comment]
The event slug is sent, as well as requiresApproval
Notice that the registration project email does not contain `verificationSentence` anymore and can be done thanks to requiresApproval. (was ```
verificationSentence: event.requiresApproval ? 'You will be contacted by the Coolest Projects team if your project is accepted.' : '',
```

**Comment by Wardormeur** [comment]
Depending on the email ... 
https://github.com/CoderDojo/coolest-platform/blob/master/server/test/unit/controllers/mailing.spec.js#L113
https://github.com/CoderDojo/coolest-platform/blob/master/server/test/unit/controllers/mailing.spec.js#L164
(https://github.com/CoderDojo/coolest-platform/blob/master/server/test/unit/controllers/mailing.spec.js#L247 && https://github.com/CoderDojo/coolest-platform/blob/master/server/test/unit/controllers/mailing.spec.js#L197 )
