### ISSUE TITLE
Redirect blog.cp.org to cp.org

### ISSUE THREAD

**Issue by Wardormeur** [CoderDojo/coolest-platform#167]
On Monday the 7th of January AM.

TBD: 
 - [x] Replace WPEngine configuration's url 
 - [x] Replace DNS entry, which deprecates the old blog
 - [x] Update site url in WP settings
 - [x] Merge and deploy https://github.com/RaspberryPiFoundation/coolestprojects.org/pull/3

**Comment by conoramurphy** [comment]
I'm not sure what the above entails exactly.
What I'm assuming/want is...
The flat generated site is root. (With the upated pr merged)
And the rest goes to the wp site.

**Comment by Wardormeur** [comment]
Yep, it "goes to" but stays on coolestprojects.org, not blog.coolestprojects.org, am I right?

**Comment by conoramurphy** [comment]
It's essentially contentless on the pages/navigation etc. Monday would be better.

**Comment by Wardormeur** [comment]
When are the pages supposed to be filled? Sunday?

**Comment by conoramurphy** [comment]
They were meant to be done already. But moving the publishing date forward won't help. They know we're going live monday. If suddenly they were much more filled out tomorrow we could do it then but unlikely.

**Comment by Wardormeur** [comment]
All good
