### ISSUE TITLE
Add hint to "Visual Programming" for "Visual Programming (such as Scratch)"

### ISSUE THREAD

**Issue by mrichardson23** [CoderDojo/coolest-platform#168]
I suggest that the following change:

In the Project category drop down box, change "Visual programming" to "Visual programming (such as Scratch)"

Rationale:

* People may not know what visual programming is
* People may not know that Scratch is considered visual programming
* People who've registered in the past may be expecting a Scratch category and this is their hint that this is where they belong.
* In case there's any legacy info floating around that refers to this category as "Scratch"

------------------------------------

The easiest way to acheive this is to change 
`You can read the category descriptions here` to `Note: Visual Programming includes Scratch. You can read all the category descriptions here`

**Comment by Wardormeur** [comment]
I think the whole "Visual Programming" is a bag of words, so specifying Scratch is doing the opposite.
I agree however : we may have to introduce an info bubble or category help (maybe a link to a static page listing the different types of categories?) to help deciding where one project fits ?

**Comment by Wardormeur** [comment]
How would that hint be represented @conor ? It's a native dropdown at the moment.
Do you mean replacing the text in the dropdown from "Visual Programming" to "Visual Programming (such as Scratch)" ?

**Comment by conoramurphy** [comment]
It's a question of time. 

If replacing the text in the dropdown is easy do 
a) replace the text in the dropdown (I don't think this is easy). 
b) If not change the hint above the drop-down that currently is a link and change it from `You can read the category descriptions here` to `Note: Visual Programming includes Scratch. You can read all the category descriptions here`

Below is my browser edited html result for option b).
```
<small><strong>Note:</strong> Visual Programming includes Scratch. <a href="http://coolestprojects.org/registration-2018/project-categories/" target="_blank">You can read the category descriptions here</a></small>
```

Make sense?

**Comment by Wardormeur** [comment]
Done with a)
