### ISSUE TITLE
Additional questions for Coolest Projects International update

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/coolest-platform#172]
Currently;
Does your project have an educational focus/aim?
Do you think your project topic is around Education?

Should be as in inputs doc;
Does your project have an educational focus/aim? 
Does your project have a social focus or does it address a societal issue? 

Last question on innovator stage is grand 👍

**Comment by Wardormeur** [comment]
Ah, that's my bad I guess.
Because it was part of a rewrite, I must have skipped that one.
Will fix
