### ISSUE TITLE
[@conoramurphy] Set up Google Data Studio reports off the CSV export for int and review with regional groups

### ISSUE THREAD

**Issue by Wardormeur** [CoderDojo/coolest-platform#175]

**Comment by Wardormeur** [comment]
I offered a solution to simplify the export. It simply require a new admin account that nobody connects to per instance.
https://raspberrypifoundation.slack.com/archives/CA2MR1SHW/p1543624064001000
Example : https://docs.google.com/spreadsheets/d/1Jj-dGkddXxwEOVJwiMZl9H4hDzxcWGZer6RAAieabrI/edit?ouid=110915340274527427019&usp=sheets_home&ths=true

**Comment by conoramurphy** [comment]
Ah cool. I think we should try it properly on 1 of them by creating a dedicated user. International is obvious. Sound good?

**Comment by Wardormeur** [comment]
On it in a few

**Comment by Wardormeur** [comment]
Done

**Comment by conoramurphy** [comment]
Is it possible to get a users one in there in the other tab as well?

**Comment by Wardormeur** [comment]
Closing, this has been done
