### ISSUE TITLE
Confirm attendance email - first sent email uses 3rd email copy ("LAST CALL")

### ISSUE THREAD

**Issue by mrichardson23** [CoderDojo/coolest-platform#181]
We used the feature to send confirmation emails for projects. The first confirmation email we sent used the subject and body which is meant for the third request.

Email subject expected: **Coolest Projects: Confirm your spot**
Email subject received: **LAST CALL for Coolest Projects**

Email body expected:
> It’s happening! And we can’t wait to see you at {{eventName}} on {{eventDate}}. We want to check in to confirm that you plan to attend and showcase {{projectName}}. Please confirm your attendance below… all it takes is one click:

Email body received:
>  Hey friend! We just want to check in about your cool project. We haven’t heard back and want to make sure you’re attending. Please let us know either way by clicking the appropriate button below. This helps ensure that we have space for all youth who want to present.

**Comment by Wardormeur** [comment]
I'm not sure the email are configured yet
cc @conoramurphy

**Comment by conoramurphy** [comment]
The confirm ones should have been. My mistake. ONe minute

**Comment by conoramurphy** [comment]
Can you forward the email to me @mrichardson23 ?

**Comment by mrichardson23** [comment]
@conoramurphy Sent.

**Comment by conoramurphy** [comment]
There was a mismatch between variables on the production site and the emails templates. Sorry about that and thanks for catching it!

Can you retest the emails now? We reset it for USA so the confirmation email sent should be the first one again, just with the correct copy now.
