### ISSUE TITLE
Confirmation email body copy after buttons - may need update

### ISSUE THREAD

**Issue by mrichardson23** [CoderDojo/coolest-platform#183]
In the confirmation email, the copy after the buttons uses the old copy:

> Confirming this makes sure you are judged correctly and get all our support on the day. If you want to do some final edits to your project you can just enter your email into https://registerusa2019.coolestprojects.org/events/usa-2019 and you'll get a link to edit your projects.
>  
> Note : if you have several projects we should have sent you several emails and you need to confirm them separately
>
> If you have any issues contact us at usa@coolestprojects.org.
>   
> Be cool,
>
> Your Coolest Projects Team

[We suggest this copy in from this document](https://docs.google.com/document/d/1IYJCiH2phLX0-uk5mwYwuHa1Zhk2jEXWgUK490o0JNM/edit):

> Note: if you have multiple projects registered, you’ll receive an email for each project. Please be sure to confirm each of them separately. 
>
> Confirming your project ensures that we’ll be ready for you on the big day. We’ll hold your table and set a swag bag aside for you. If you want to make any final edits to your project, visit the <a href=”{{eventURL}}”>event registration page</a>. 
>
> If you have any questions, contact us at {{eventContact}}.
>
> Be cool,
> Your Coolest Projects Team

**Comment by conoramurphy** [comment]
Yes sorry. There was a confusion in the interface that wiped this the last time I did it.

Can you retest the emails now? We reset it for USA so the confirmation email sent should be the first one again, just with the correct copy now.
