### ISSUE TITLE
Suggestion: soften copy when someone cancels their project

### ISSUE THREAD

**Issue by mrichardson23** [CoderDojo/coolest-platform#184]
When a user clicks the link to cancel their project from the confirmation email, they see the copy:

> **Your project has been canceled.**
> That's a shame, see you next year maybe?

"That's a shame" reads as a bit harsh to us. Suggesting:

> **Your project has been canceled.**
> See you next year, maybe?

**Comment by conoramurphy** [comment]
Possibly makes sense. However, at this stage, we're using the standard that we're only changing copy with a direct use case we're worried about. I don't see any real issue this could cause. I'll close now, you can reopen it if this causes a problem.
