### ISSUE TITLE
Avatar for usa@coolestprojects.org is not the logo

### ISSUE THREAD

**Issue by mrichardson23** [CoderDojo/coolest-platform#187]
Emails from usa@coolestprojects.org show an avatar of Amy when viewed in Gmail mobile (see screenshot below). It should be the CP logo. I know this is not a Coolest Platform issue per se and is likely a Gsuite configuration issue for that account, but wanted to make sure this is tracked somewhere until it's solved. Please feel free to close if it shouldn't be here.

![img_8470](https://user-images.githubusercontent.com/274367/49945091-ef435a00-fee3-11e8-8680-f9b94c95c43b.PNG)

**Comment by conoramurphy** [comment]
Sure you can track it here for the time being. You can send this link to IT support or something?

**Comment by mrichardson23** [comment]
Fixed.
