### ISSUE TITLE
Event time incorrect on confirmation page

### ISSUE THREAD

**Issue by mrichardson23** [CoderDojo/coolest-platform#188]
When an individual confirms their project from the email link, the time listed is incorrect. It should be 9am:

![screen shot 2018-12-14 at 8 18 25 am](https://user-images.githubusercontent.com/274367/49991447-fc5e5880-ff78-11e8-8e4f-17c2ff2453a6.png)

**Comment by Wardormeur** [comment]
Hey @mrichardson23 , just to exclude a scenario : is it correct on the homepage ?

**Comment by mrichardson23** [comment]
@Wardormeur No, it's incorrect on the registration homepage as well:
> **Register or edit a project for Coolest Projects USA 2019 which will be held on Saturday, March 23, 2019 2:00 AM PDT at the Discovery Cube, Orange County.**

**Comment by Wardormeur** [comment]
Cool, that's what I thought :) 
It's a configuration + timezone issue, doesn't reflect on Dublin/London as they share the same. Will fix in a few

**Comment by Wardormeur** [comment]
Can you verify if this solves it @mrichardson23 ?

**Comment by mrichardson23** [comment]
It now says:

> The registration for Coolest Projects USA 2019 has now closed. Please contact usa@coolestprojects.org if you have any questions.

**Comment by Wardormeur** [comment]
My bad, I'm not yet in 2019 in my head. Could you try again please?

**Comment by mrichardson23** [comment]
It now says:

> Register or edit a project for Coolest Projects USA 2019 which will be held on Friday, March 22, 2019 7:00 PM PDT at the Discovery Cube, Orange County.

It should March 23, 2019 at 9:00 AM PDT.

**Comment by Wardormeur** [comment]
Arrgh, it's -7, not +7. I'm very sorry.

**Comment by Wardormeur** [comment]
Closing, verified on slack :+1: 
Thanks for your patience !
