### ISSUE TITLE
Line breaks in the confirm your project email

### ISSUE THREAD

**Issue by mrichardson23** [CoderDojo/coolest-platform#189]
Below the buttons in the confirm your project, there are line breaks between "Confirming" / "your" in "Confirming your project ensures that" and "if" / "you" in "If you have any questions."

See screenshot:

![screen shot 2018-12-14 at 8 25 37 am](https://user-images.githubusercontent.com/274367/49991724-e0a78200-ff79-11e8-8c2b-0895e10fa9fd.png)

**Comment by mrichardson23** [comment]
This may have been fixed? The screenshot above is from email 1 sent yesterday at 3pm. I just sent email 2 now and line breaks look fine.

**Comment by conoramurphy** [comment]
Looks fixed. hard to remember now why it broke.
