### ISSUE TITLE
Android input broken : Can't enter text into inputs on 2nd page on android

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#197]
**What happened**
On 2 android phones (Galaxy A3 and Nokia 7 plus, so Android 8.x and 9.x respectively) text cannot be entered in any text fields on the second page (title description, name of people etc.). The first page, email of creator, works as expected. 

**Detail**

_devices_ Does not work on On 2 android phones (Galaxy A3 and Nokia 7 plus, so Android 8.x and 9.x respectively). Tested on a one plus that is on android 9.x and it works fine (different browser?). Iphone works fine as well...

_More detail on what happened_ On the second page as you type suggestions come up and validation is triggered slightly so it's in focus but validation doesn't go away if you keep typing so the text is definitely not going in, (not just can't be seen or anything).

The dropdown on club selector is also stopped working, allows text in but the filter is not working, maybe related I don't know. 

_Debugging tried_
I debugged using chrome remote debugger on the club selector and got "Cannot read property 'place' of undefined" after a bit but don't think that's the issue.

Weirdly I triggered some correct validation (input too long) using paste but the text still did not appear in the field. And it's not just invisible with css it's not there as I can't delete it then or anything. Some vue.js weirdness?

**URLs**
First page : https://register-international-2019.coolestprojects.org (input works)
Fill in a test email in the first page and you get to the second page where the inputs stop working.
https://register-international-2019.coolestprojects.org/events/int-2019/projects/create

**Comment by dtt101** [comment]
@conoramurphy - can you drop a URL in the issue? For the uninitiated.

**Comment by conoramurphy** [comment]
@dtt101 apologies, updated

**Comment by conoramurphy** [comment]
**Update after Davids investigation**
David looked into this on Android emulator and believes the input is being caught by the vaildator https://github.com/baianat/vee-validate/.

I'm also linking https://github.com/baianat/vee-validate/issues/1490 from that library as it lists a few potential solutions.

**Comment by dtt101** [comment]
Thanks for updating @conoramurphy

**Comment by conoramurphy** [comment]
Fixed by @ArayB in https://github.com/CoderDojo/coolest-platform/pull/198
