### ISSUE TITLE
Close down coolest projects 2019 platforms

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#205]
**Business goal**
Do the appropriate cleanup for Coolest Projects 2019 series of events

**To do**
- [x] Review that all teams have a clean google sheets export of their platforms databases for future analysis
- [x] Update redirect rules (or remove cnames) to point https://register-international-2019.coolestprojects.org/* and https://registerusa2019.coolestprojects.org/* and https://register-uk-2019.coolestprojects.org/* to coolestprojects.org
- [x] Update the Int `Tickets` button https://coolestprojects.org/ to say `Read More` but link to the same page
- [x] Cleanup LastPass details for coollest projects
- [x] Sanit review the above has been done
- [x] Shut down all coolest platforms 
- [x] Shut down coolest databases. 🔥

**Comment by josephwilk** [comment]
I think we need to buy more `page rules` in Cloudflare to add the redirections. Thats an additional $5/month. @grega Might know a better way with Cloudflare that I'm missing.

**Comment by josephwilk** [comment]
I think the only thing left that I'm unsure on is shutting down any web servers. I've shutdown machines for the DB, but looking through the Ec2 instances its unclear if there is or isn't a webserver for coolestprojects:
![image](https://user-images.githubusercontent.com/9792/60976099-04bb1e00-a325-11e9-8c55-581c680838e5.png)

**Comment by DanielBrierton** [comment]
coolest-platform is just deployed to the same Kubernetes cluster as Zen, so there's no EC2 instances to kill. To take down the actual platform, some `kubectl` is needed

**Comment by josephwilk** [comment]
😭 Ok, thanks for the info.

**Comment by DanielBrierton** [comment]
Really, I don't see any point removing them from k8s, it's handy enough to have them there and update the DB details when rolling out for the next Coolest Projects. It's not costing us anything to have them sitting there with Zen.

**Comment by josephwilk** [comment]
Yes agreeded, though the more important side effect is having the knowledge to see and prod at the Kubernete's cluster. At the moment it's a black box of woe and misery.

**Comment by DanielBrierton** [comment]
Pretty sure once you're set up with kubectl, then it's just a case of

```
kubectl scale --replicas=0 deployment/coolest-platform --namespace=coolest-namespace
```
to turn it off, then just the same but >0 for the replicas to turn it back on. Ideally though, this should be done through a version controlled set of config files. That's been started, but unfortunately not completed. https://github.com/CoderDojo/k8s-config/pull/2

**Comment by josephwilk** [comment]
coolest-platform is no longer on Kubernetes: 

![Screenshot 2019-07-11 at 18 24 52](https://user-images.githubusercontent.com/9792/61071817-f09d1c80-a409-11e9-9ed6-26db5d0c8852.png)
