### ISSUE TITLE
Show db set values to admins

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#206]
**Business Goal**
Reduce admin time and errors by not having key values hidden in the database. The last 2 years there have been several mistakes as these dates change quite dynamically and are hard to keep track of across 3 similar dated events across 2 different timezones. If you can't simply view the dates, mistakes will be made and platforms will close at the wrong times etc.

**Notes**
There are several key Database values that set when setting up a new instance of the platform but are not visible in the frontend.

These include but are possibly not exhaustive to
- [ ] Open, registration closed and editing closed dates
- [ ] Addresses, venue names, event name etc.

**Task**
Show these values in the footer of the admin panel so any logged in the admin can double check these values without submitting a request.

**Comment by ArayB** [comment]
Completed in #229
