### ISSUE TITLE
Coolest projects homepage: Update wording on registration

### ISSUE THREAD

**Issue by nuala-louise** [CoderDojo/coolest-platform#209]
https://coolestprojects.org/

Update text in purple "PROJECT REGISTRATION NOW OPEN!" box to:

> PROJECT REGISTRATION OPENING SOON!
> Coolest Projects recognises the effort and creativity of young people who take an idea and make it a reality. All projects are welcome, from beginner to advanced. Join us and share your Scratch animation, website, game, robot, or anything else you’ve built with technology.
> 
> Button: JOIN OUR MAILING LIST FOR UPDATES!
> Link: https://raspberrypi.us9.list-manage.com/subscribe?u=54fbc2c9ac9d9dd634725107a&id=1ec0029928

**Comment by nyashamaphosa** [comment]
### **Text and link changed** 
<img width="1408" alt="Screenshot 2019-09-04 at 15 56 07" src="https://user-images.githubusercontent.com/14819641/64266468-8c3f9a80-cf2c-11e9-8eda-debfcb4eb662.png">
