### ISSUE TITLE
Update video on the homepage to 2020 dates video.

### ISSUE THREAD

**Issue by nuala-louise** [CoderDojo/coolest-platform#210]
Hey there. 
It would be great if the video on the homepage (coolestprojects.org) could be updated to this new video for Coolest Projects 2020:
https://www.youtube.com/watch?v=ms3c7VUBBG0

Thank you!

**Comment by nuala-louise** [comment]
Hey @conoramurphy any chance this could be looked at? Sarah is looking for it to be updated for sponsors going to the page.

**Comment by DanielBrierton** [comment]
Hey @nuala-louise. That video's been removed, but I'm guessing it should be this one? https://www.youtube.com/watch?v=ipcbm3tzcDE

**Comment by DanielBrierton** [comment]
@nuala-louise Updated and live now :)
