### ISSUE TITLE
Give admin access to the following people

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#215]
#### Add the following people as CP admins

*NA:* 
helen.drury@raspberrypi.org
christina@raspberrypi.org
dana@raspberrypi.org
matt@raspberrypi.org

*UK:* 
helen.drury@raspberrypi.org
tom.evans@raspberrypi.org

*INT:* 
helen.drury@raspberrypi.org
rosa@raspberrypi.org
vanessa.greene@raspberrypi.org

**Comment by ArayB** [comment]
Access provided.
