### ISSUE TITLE
Update the platforms with the correct images

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#218]
- [x] Conor to do the emails.
- [x] Someone else do the platforms

**Comment by conoramurphy** [comment]
![Coolest_Projects_Google_Forms_Logos_INT](https://user-images.githubusercontent.com/3603234/68592799-cfb60800-048b-11ea-9886-e2ef7fbff492.png)
![Coolest_Projects_Google_Forms_Logos_USA](https://user-images.githubusercontent.com/3603234/68592800-cfb60800-048b-11ea-9281-cf21ccff537d.png)
![Copy of Coolest_Projects_2019_UK_Logo_Lar (1)](https://user-images.githubusercontent.com/3603234/68592801-cfb60800-048b-11ea-9eb2-3a3ee662a88b.png)

**Comment by conoramurphy** [comment]
[Coolest_Projects_Google_Forms_Logos_LARGE-01.svg.zip](https://github.com/CoderDojo/coolest-platform/files/3832000/Coolest_Projects_Google_Forms_Logos_LARGE-01.svg.zip)

SVG for the platforms

**Comment by ArayB** [comment]
Updated the platform.
