### ISSUE TITLE
Fix duplicate project being created

### ISSUE THREAD

**Issue by Wardormeur** [CoderDojo/coolest-platform#85]
When the user click on "register" after having filled in the information for the project, members and supervisor; if the user presses the navigation button "back", and click register again to go back to the extra-details; then the project is created twice.
To avoid that, the navigation should pass back and forth the project; or use Vuex to keep the current state of the flow.

**Comment by Wardormeur** [comment]
@conoramurphy what's the expected behavior here?
If it's completed, go back to the project listing, or let the user come back to the page as an edit ?

**Comment by conoramurphy** [comment]
I would expect to allow them to edit the project. But if there's a significant difficulty between those two I don't mind which. Both are reasonable.

**Comment by Wardormeur** [comment]
@conoramurphy I can't reproduce : the fields are flushed, so it counts as a new project.
If I remember well, the bug was with very similar data, which I can't see happening when you have to refill everything.
Is this really a bug or an inconvenience that we want to fix ?

**Comment by conoramurphy** [comment]
You can leave it for now and I'll see once I do a proper test can I reproduce.
