### ISSUE TITLE
Have several different confirm emails

### ISSUE THREAD

**Issue by conoramurphy** [CoderDojo/coolest-platform#99]
### Business Case

Our experience for international and NA is that 3 rounds of the current confirm email we're currently at about 60-80% rate of confirmations depending on the event. If we could improve the rate of confirmations it would save a lot of manual pre-event work.

### Need
In Coolest Platform you currently can click "Send confirm emails" and a sengrid template with confirm/cancel buttons is sent to all pending projects (they then click confirm/cancel and their status is updated on the platform).

What we want to do is try to have 3 different templates with different messaging to see if that improves significantly the conversion rate.

The platform would doing the exact same task as currently except for incrementing a counter after you send the confirmation email and send a different template id for each increment (for round 1,2 & 3). After 3 increments it just keeps sending the third template.

Can we investigate the feasibility of this?

Can we verify who's being sent the email.

**Comment by Wardormeur** [comment]
Do we agree we're fine reusing the same template and making use of dynamic templates to make the string changes on Sendgrid ?
I can change the email tag as well so we know what's the opening rate for each step.
@conoramurphy

**Comment by conoramurphy** [comment]
Yes I'm fine with that as long as we can change the email tag to compare open rates.

**Comment by conoramurphy** [comment]
Can you just confirm the variable you'll be sending in each case then for the dynmaic template?

**Comment by Wardormeur** [comment]
I opened a ticket to document them so you don't have to crawl in the tests/code
